---
name: nessus_trigger
description: Webhook trigger for Nessus
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "nessushook"

action:
  ref: "banzai.nessus_chain"
  parameters:
    url: "{{trigger.body.url}}"
    testid: "{{trigger.body.testid}}"
    scantype: "{{trigger.body.scantype}}"
